### signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@acme.com",
  "password": "test",
  "roles": []
}

### signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test@acme.com",
  "password": "test"
}

### refresh
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RAYWNtZS5jb20iLCJzdWIiOiI2OTI5ZmE5ZC0zZWI1LTQ2OWItYWU0MC02NGEwMzczYjEyMzYiLCJyb2xlcyI6W10sInR5cGUiOiJyZWZyZXNoIiwiaWF0IjoxNzIwNDU2MjUwLCJleHAiOjE3MjA0NTk4NTB9.T9dfyfXy76m6Y-AE8yMT0nziD1baR8NAKlYL5bToJ9I"
}
