### signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@acme.com",
  "password": "test",
  "roles": []
}

### signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test@acme.com",
  "password": "test"
}

### refresh
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RAYWNtZS5jb20iLCJzdWIiOiJmMTI1Y2M2OC0wYzdhLTQyYTgtYmU5Ny1lZWY5YThmNWJkM2YiLCJyb2xlcyI6W10sInR5cGUiOiJyZWZyZXNoIiwiaWF0IjoxNzIwNDU3MTcyLCJleHAiOjE3MjA0NjA3NzJ9.VOPZb0fvpVK7PA9Gqiht_YXbDHjcexLH1ko4ITUaWSk"
}
